POST http://localhost:3001/api/users
Content-Type: "application/json"

{
    "username": "Fab",
    "password": "prova",
    "role": "patient"
}
###

POST http://localhost:3001/api/users/login
Content-Type: "application/json"

{
    "username": "Pietro",
    "password": "prova"
}

###
GET http://localhost:3001/api/test/pharmacy/94ae7246-40c6-40fa-8d5a-fcc34d0edbca
###
GET http://localhost:3001/api/test/doctors/prescription/94ae7246-40c6-40fa-8d5a-fcc34d0edbca

###
GET http://localhost:3001/api/test/doctors/name/94ae7246-40c6-40fa-8d5a-fcc34d0edbca

###
GET http://localhost:3001/api/test/doctors/surname/94ae7246-40c6-40fa-8d5a-fcc34d0edbca

###
GET http://localhost:3001/api/test/doctors/hospital/94ae7246-40c6-40fa-8d5a-fcc34d0edbca

###
GET http://localhost:3001/api/test/doctors/specialization/94ae7246-40c6-40fa-8d5a-fcc34d0edbca

###
POST http://localhost:3001/api/test/doctors/prescriptions
Content-Type: "application/json"

{
    "DoctorID": "94ae7246-40c6-40fa-8d5a-fcc34d0edbca",
    "PatientID": "94ae7246-40c6-40fa-8d5a-fcc34d0edbc3a",
    "Drugs": ["Tachipirina", "Aspirina"],
    "Description": "Due scatole da 500",
    "Status": "pending"
}