POST http://localhost:3001/api/users
Content-Type: "application/json"

{
    "username": "Fab",
    "password": "prova",
    "role": "patient"
}
###

POST http://localhost:3001/api/users/login
Content-Type: "application/json"

{
    "username": "Fra",
    "password": "prova"
}

###
GET http://localhost:3001/api/users/Pietro
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBpZXRybyIsInBhc3N3b3JkIjoicHJvdmEiLCJpYXQiOjE2OTYxODI3NTQsImV4cCI6MTY5NjE4NjM1NH0.WIgmoreoc_q_RuRGWT0gt5TLyvOascm7uqMufv9sOCE
